import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# Bind to 0.0.0.0 so the server is reachable from the host when Phoenix runs
# inside the Docker container (loopback-only would hide it behind the port map).
config :astro_playground, AstroPlaygroundWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  # Hybrid dev stack: the frontend build/watch runs on the HOST via mise, not
  # from Phoenix (this container has no node). Assets land in priv/static and are
  # picked up by live_reload below.
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :astro_playground, AstroPlaygroundWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/astro_playground_web/views/.*(ex)$},
      ~r{lib/astro_playground_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :astro_playground, AstroPlayground.Repo,
  username: "postgres",
  password: "postgres",
  database: "astro_playground_dev",
  hostname: System.get_env("DATABASE_HOST") || "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10
